const exception = Math.pow(NaN, 0);
console.log(exception);